name: chronos
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - pyarrow
  - pytorch
  - numpy
  - tifffile
  - google-api-python-client
  - google-auth-httplib2
  - google-auth-oauthlib
  - zarr
  - fsspec
  - requests
  - scikit-learn
  - pip:
    - torch
    - mamba-ssm-macos


