import torch
import torch.nn as nn
import torch.nn.functional as F
from mamba_ssm import Mamba
from src.config import settings

import logging
logger = logging.getLogger(__name__)


class StateSpaceEngine(nn.Module):
    """
    StateSpaceEngine models the continuous kinetic trajectory of the biological state using 
    a Mamba SSM.
    It implements a self-supervised Forward Predictive Coding loop.
    """

    def __init__(self, d_model=settings.MAMBA_D_MODEL, expand=2, d_conv=4, d_state=settings.MAMBA_D_STATE):
        """
        Args:
            d_model (int): The dimension of the input feature vectors (e.g., 768 for optical).
            expand (int): Expansion factor creating the inner dimension (width of data pathway).
            d_conv (int): The kernel size of the local 1D convolution applied before the SSM.
            d_state (int): The size of the hidden state / recurrent memory (depth of memory).
        """
        super().__init__()
        # Instantiate a standard 1D Mamba block from mamba_ssm. 
        # The internal architecture:
        # - Expand (Linear Projection)
        # - 1D Conv
        # - Activation Function
        # - Selective Scan (SSM)
        # - Project back
        self.mamba = Mamba(d_model=d_model, d_state=d_state, d_conv=d_conv, expand=expand)

        # Forward Predictive Coding / Latent Dynamics Prediction
        # Maps hidden state at time t -> predicted embedding at time t+1
        self.forward_predictor = nn.Linear(d_model, d_model)

    def forward(self, x):
        """
        Args:
            x (torch.Tensor): Sequence of spatial embeddings of shape [Batch, Time, 768]
                              generated by the SpatialCompressor.

        Returns:
            tuple:
                - loss (torch.Tensor): Scalar loss for backpropagation (MSE + Mean Cosine Distance)
                - frame_distances (torch.Tensor): 1D array of frame-by-frame 
                  Cosine Distances [Time-1]
        """
        # Ingest the sequence of spatial embeddings [Batch, Time, 768]
        # Pass through Mamba block to generate contextualized hidden states
        hidden_states = self.mamba(x)

        # Map each hidden state to a predicted embedding
        predictions = self.forward_predictor(hidden_states)

        # Calculate predictions against actual embedding at time t+1
        # predictions at time t predict x at time t+1
        preds_t = predictions[:, :-1, :]  # Shape: [Batch, Time-1, 768]
        target_t = x[:, 1:, :]  # Shape: [Batch, Time-1, 768]

        # Mean Squared Error (MSE)
        mse_loss = F.mse_loss(preds_t, target_t)

        # Cosine Distance = 1 - Cosine Similarity
        # cosine_similarity returns shape [Batch, Time-1]
        cos_sim = F.cosine_similarity(preds_t, target_t, dim=-1)
        cos_dist = 1.0 - cos_sim

        # Scalar loss for backpropagation
        # We can combine MSE and the mean of the Cosine Distance
        mean_cos_dist = cos_dist.mean()
        scalar_loss = mse_loss + mean_cos_dist

        # Frame-by-frame Cosine Distances: Average over the Batch dimension 
        # -> 1D array of length Time-1
        frame_distances = cos_dist.mean(dim=0)

        return scalar_loss, frame_distances


if __name__ == "__main__":
    logger.info("Testing StateSpaceEngine architecture...")
    from src.utils.device import get_optimal_device
    device = get_optimal_device(verbose=True)
    logger.info(f"Using device: {device}")

    try:
        model = StateSpaceEngine().to(device)

        # Dummy input: [Batch, Time, 768]
        batch_size = 2
        time_steps = 10
        x = torch.randn(batch_size, time_steps, 768).to(device)

        loss, ksm_metric = model(x)

        logger.info(f"Input shape: {x.shape}")
        logger.info(f"Scalar Loss: {loss.item():.4f}")
        logger.info(f"KSM Metric (Frame-by-frame Cosine Distances) shape: {ksm_metric.shape}")
        logger.info("Test passed! Requirements satisfied.")
    except Exception as e:
        logger.error(f"Test failed or skipped due to environment constraints: {e}")
